name: Deploy NodeJS Application to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/smtg
            git pull origin main
            docker stop $(docker ps -q) || true
            docker rm $(docker ps -aq) || true
            docker build -t smtg .
            docker run -d -p 80:8080 smtg